import java.util.Scanner;
import java.util.ArrayList;

public class RunNeuralNetwork
{
    //features
    private static Scanner userScanner = new Scanner ( System.in );
    private static NeuralNetwork neuralNetwork = new NeuralNetwork ( );
    
    public static void main ( String [ ] aiStuff )
    {
        doTraining ( );
        doTesting ( );
    }
    
    //do training
    public static void doTraining ( )
    {
        ArrayList <String> trainingData = getTrainingData ( );
        
        for ( int tDI = 0; tDI < trainingData.size ( ); tDI ++ )
        {
            String [ ] inputs = trainingData.get ( tDI ).split ( "::" );
            int inputPartI = Integer.parseInt ( inputs [ 0 ].split ( "," ) [ 0 ]  );
            int inputPartII = Integer.parseInt ( inputs [ 0 ].split ( "," ) [ 1 ] );
            
            //forward prop takes as input, the input signals
            neuralNetwork.doForwardPropagation ( new int [ ] { inputPartI, inputPartII } );
            
            //back prop takes target
            int target = Integer.parseInt ( trainingData.get ( tDI ).split ( "::" ) [ 1 ] );
            neuralNetwork.doBackwardPropagation ( target );
        }
    }
    
    //do test 
    public static void doTesting ( )
    {
        System.out.println ( "Neural Network Lecture JAIA 3-21-2020 8:28 pm by God Bennett ");
        System.out.println ( "1. Get neural network answer for input [0,0] " );
        System.out.println ( "2. Get neural network answer for input [0,1] " );
        System.out.println ( "3. Get neural network answer for input [1,0] " );
        System.out.println ( "4. Get neural network answer for input [1,1] " );
        System.out.println ( "5. Leave program " );
        int userInput = userScanner.nextInt ( );
        
        switch ( userInput ) 
        {
            case 1: 
            {
                int [ ] inputs = new int [ ] { 0, 0 };
                
                neuralNetwork.doForwardPropagation ( inputs );
                
                System.out.println ( "Neural network answer for input [0,0] " + neuralNetwork.getOutcome ( ) );
                
                returnToMainMenu ( );
            }
            break;
            case 2: 
            {
                int [ ] inputs = new int [ ] { 0, 1 };
                
                neuralNetwork.doForwardPropagation ( inputs );
                
                System.out.println ( "Neural network answer for input [0,1] " + neuralNetwork.getOutcome ( ) );
                
                returnToMainMenu ( );
            }
            break;
            case 3: 
            {
                int [ ] inputs = new int [ ] { 1, 0 };
                
                neuralNetwork.doForwardPropagation ( inputs );
                
                System.out.println ( "Neural network answer for input [1,0] " + neuralNetwork.getOutcome ( ) );
                
                returnToMainMenu ( );
            }
            break;            
            case 4: 
            {
                int [ ] inputs = new int [ ] { 1, 1 };
                
                neuralNetwork.doForwardPropagation ( inputs );
                
                System.out.println ( "Neural network answer for input [1,1] " + neuralNetwork.getOutcome ( ) );
                
                returnToMainMenu ( );
            }
            break;            
        }
    }
    
    //return main menu/testing
    public static void returnToMainMenu ( )
    {
        userScanner.nextLine ( );
        userScanner.nextLine ( );
        System.out.println ( "\f" );
        doTesting ( );
    }
    
    //training data
    public static ArrayList <String> getTrainingData ( )
    {
        ArrayList <String> returnValue = new ArrayList <String> ( );
        
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "1,1::0" );
        returnValue.add ( "0,0::0" );
        returnValue.add ( "0,1::1" );
        returnValue.add ( "1,0::1" );
        returnValue.add ( "1,1::0" );
        
        return returnValue;
    }
}
